<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RDBModel" nsURI="https://org/eclipse/RDBModel" nsPrefix="RDBModel">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Database">
    <eStructuralFeatures xsi:type="ecore:EReference" name="tables" upperBound="-1"
        eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="database"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Table">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="uniqueName uniqueColumnNames"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="uniqueName" value="Table.allInstances()->isUnique(e | e.name)"/>
      <details key="uniqueColumnNames" value="columns->isUnique(e | e.name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//Column" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="primaryKey" eType="#//PrimaryKey"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="foreignKeys" upperBound="-1"
        eType="#//ForeignKey" containment="true" eOpposite="#//ForeignKey/sourceTable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Column">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="typeMustBeSet"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="typeMustBeSet" value="type &lt;> DataType::Null"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DataType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNullable" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnique" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PrimaryKey">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="notNull"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="notNull" value="columns->size() = columns->select(not isNullable)->size()"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="columns" lowerBound="1"
        upperBound="-1" eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ForeignKey">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="columnInSource columnInTarget sameTypeKeys validFK"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="columnInSource" value="sourceTable.columns->select(c | c.name = sourceColumn.name)->size() = 1"/>
      <details key="columnInTarget" value="targetTable.columns->select(c | c.name = targetColumn.name)->size() = 1"/>
      <details key="sameTypeKeys" value="sourceColumn.type = targetColumn.type"/>
      <details key="validFK" value="(not targetColumn.isNullable and targetColumn.isUnique)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;or (targetTable.primaryKey.columns->select(c | c.name = targetColumn.name)->size() = 1 and targetTable.primaryKey.columns->size() = 1)&#xA;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;&#x9;or (targetTable.primaryKey.columns->select(c | c.name = targetColumn.name)->size() = 1 and targetColumn.isUnique)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceTable" lowerBound="1"
        eType="#//Table" eOpposite="#//Table/foreignKeys"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetTable" lowerBound="1"
        eType="#//Table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceColumn" lowerBound="1"
        eType="#//Column"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetColumn" lowerBound="1"
        eType="#//Column"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DataType">
    <eLiterals name="Null" literal="Null"/>
    <eLiterals name="RDBInteger" value="1" literal="RDBInteger"/>
    <eLiterals name="RDBReal" value="2" literal="RDBReal"/>
    <eLiterals name="RDBString" value="3" literal="RDBString"/>
    <eLiterals name="RDBBoolean" value="4" literal="RDBBoolean"/>
    <eLiterals name="RDBDate" value="5" literal="RDBDate"/>
    <eLiterals name="RDBTime" value="6" literal="RDBTime"/>
  </eClassifiers>
</ecore:EPackage>
